# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { 'postgres' } %>
  password: <%= ENV.fetch("PGPASSWORD") { 'password' } %>
  host: <%= ENV.fetch("PGHOST") { '127.0.0.1' } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>
  
development:
  <<: *default
  database: family_habit_development